name: Java CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # triggers on tags starting with 'v'

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/Calculator-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
